### ISSUE TITLE
really cool, but i have a few questions

### ISSUE THREAD

**Issue by maksw2** [Aermoss/VEGA#1]
1. can i load multiple models
2. platform support (windows,linux,macos)
3. architecture support (64bit,32bit,arm,arm64)
4. how to exit with a keypress

**Comment by Aermoss** [comment]
sorry for seeing this very late, if you're still wondering:

1. yes, you can load multiple models like this:
```
std::vector<vega::VEGAModel*> models; 
models.push_back(new vega::VEGAModel("res/models/crow/scene.gltf"));
models.push_back(new vega::VEGAModel("res/models/sword/scene.gltf"));

...

for (vega::VEGAModel* model : models)
    model->render(shader, &camera);

...

for (vega::VEGAModel* model : models) {
    model->destroy();
    delete model;
} models.clear();
```

2. i haven't tried to compile it on linux or an other platform other than windows before, but even if it fails i don't think it would be hard to set it up because it doesn't have that much platform dependent code.

3. i don't think it will support any architecture other than x64 in the future, but i plan to work on this in my newer engines like nickel that I'm still working on.

4. you can exit the program by breaking the loop with a keypress:
```
if (window.input->getKey(VEGA_KEY_ESCAPE))
    break;
```

**Comment by maksw2** [comment]
@Aermoss Thanks! Any tips on making the models? Can i just export them with blender?

**Comment by Aermoss** [comment]
Yes, you can use the models you export from blender as gltf but since the current model loader is very basic, it cannot load every model but you can overcome this problem by implementing the [assimp](https://github.com/assimp/assimp) library. Here's an example from another engine of mine: https://github.com/Aermoss/Nickel2/blob/main/src/Nickel2/Renderer/Mesh.cpp
